name: CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  client:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: grant execute permission for client/gradlew
      run: chmod +x client/gradlew
    - name: build client
      working-directory: ./client
      run: ./gradlew build

  server:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: grant execute permission for server/gradlew
      run: chmod +x server/gradlew
    - name: build server
      working-directory: ./server
      run: ./gradlew build
